"""
Django settings for hollybank project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import environ
import os
import sys

root = environ.Path(__file__) - 2  # two folders back (/a/b/ - 3 = /)
env = environ.Env(DEBUG=(bool, False),
                  USE_MAILCATCHER=(bool, False),
                  TRAVIS=(bool, False),
                  HEROKU=(bool, False),
                  )
environ.Env.read_env(root('hollybank/.env'))  # reading .env file
BASE_DIR = root()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
if SECRET_KEY is None:  # pragma: no cover
    print("No secret key!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
# when env variable is changed it will be a string, not bool
if str(DEBUG).lower() in ['true', 'on']:  # pragma: no cover
    DEBUG = True
else:   # pragma: no cover
    DEBUG = False

ALLOWED_HOSTS = [".herokuapp.com", '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'debug_toolbar',
    'django_extensions',
    'web',
    # 'activitylog',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SITE_ID = 1


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
)

ROOT_URLCONF = 'hollybank.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hollybank.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

if env('HEROKU'):
    import dj_database_url
    DATABASES = {'default': dj_database_url.config()}
else:
    DATABASES = {'default': env.db()}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = root('collected-static')

MEDIA_URL = '/media/'
MEDIA_ROOT = root('media')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'hollybank@gmail.com'
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', None)
if EMAIL_HOST_PASSWORD is None:  # pragma: no cover
    print("No email host password provided!")
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'hollybank@gmail.com'
SUPPORT_EMAIL = 'rebkwok@gmail.com'


# #####LOGGING######
if not env('HEROKU'):
    LOG_FOLDER = env('LOG_FOLDER')

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '[%(levelname)s] - %(asctime)s - %(name)s - '
                          '%(message)s',
                'datefmt': '%Y-%m-%d %H:%M:%S',
            }
        },
        'handlers': {
            'file_app': {
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': os.path.join(LOG_FOLDER, 'hollybank.log'),
                'maxBytes': 1024*1024*5,  # 5 MB
                'backupCount': 5,
                'formatter': 'verbose'
            },
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose'
            }
        },
        'loggers': {
            '': {
                'handlers': ['console', 'file_app'],
                'level': 'WARNING',
                'propagate': True,
            },
            'banking': {
                'handlers': ['console', 'file_app'],
                'level': 'INFO',
                'propagate': False,
            },

        },
    }


# ####HEROKU#######
HEROKU = env('HEROKU')


# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# MAILCATCHER
if env('USE_MAILCATCHER'):  # pragma: no cover
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = '127.0.0.1'
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False


# DJANGO DEBUG TOOLBAR
if DEBUG and 'test' not in sys.argv:  # pragma: no cover
    def show_toolbar(request):
        return True
    DEBUG_TOOLBAR_PATCH_SETTINGS = False
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": show_toolbar,
    }


JSON_KEYFILE_DICT = {
  "type": "service_account",
  "project_id": "pocketmoney-150113",
  "private_key_id": env('JSON_KEYFILE_PRIVATE_KEY_ID'),
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCj+aTTs60JpQoS\n1mcYZhabZucsAuWcLEtHeRC1a78jUEUT0d0SX1E5bl65k+HYbRKxywSpp/3w38bA\nlUS1CW+A31MZK0Yv2WIiVDaK7kYv27rJ111kzMzvQ88x5yexgqUinsxtrt9ptkbL\nWnU6jViYfoLxYS86m9t/loD67AV7d4aZ9RML+ehOm8VJT9NrKEac9AOZWYJNkOh5\nOdINfCdA/ooZlJ6hv6GbCXhZwVDPn2WuqbT4QC6/kigY8t0ylCNEOkUC7H9QFq8w\n/sEYOzdTFRkvUTtHuObTPMicVlvdAU2VMHwz0sPFvk/bc4wzFeL+6TXGjWn+Gtin\nXct4o/5HAgMBAAECggEAIfKNLUcFi/mfHEdHEMYR6BplwbbX0n1ZGHL4ApdL+wOj\nSXcpTaRuLHWtJr53A1eRhz2AuZ8N89BgVX6Ruuk5LHUPvyY2YbGfn3vPzvOFlGLp\nSOBNdZDw3JgtTSeOEDH7/i7iI9MQbdJO1crkejrJHMkUUuTL4lZiGwgNq+UxPV4s\nk1YFNU04/kJ32EbVCirhp1KDkIs8IYEmCNe6kvWHM/HjB5yxHXuw4LVL+7l8zLV4\nI6B1V/4ZbjA6PtDHDRYloeJS88FEkVp3A2xfjIpJIADFm+byEO5vYa2u8L4Qq+a5\nt8+DQjgS15YD7SfH8B48UZDteqrl5j0HZmsYnMKAAQKBgQDWcwlp7/JFao4NtyVL\n75xovNDm0ROPFZqWbbl8Ayn1VvIQNLmWo2cUrS7Z6RzspIS6Tmr/n3CACFhD45wJ\n3bru84C5YcvOPjyCcFpsaI00OnQzv0G9YVwMdOmDZqdAnOF79dzTgQVLyUivsps3\nf6FH0Efl31dq6l24YK6T+alChwKBgQDDvwXDdj+EfEpH+NUlWbyMoFxD+Eu/qFC+\niSDgGlGzi/2NVl7KhL7ryh1l98jCPXn5ZJxtCVmeLpdRNSGVLt0T3KZvcHG+AFxu\nmopP/WGHIOUESv5SlNgEVB3TIE552tpHYsZ4D98vPOVojXRPa31tmdoVuN07IZIA\nNgiX85mWQQKBgQCt/EkP9Qe3f/reb8/HqxBX/ZDzI3/d36Y7E6ygS6TYEwFzWoOU\nDuCL6vIPA81exR+WVBcFa6MHjT2nXtvzOTz3rwGp5glHPEE1htgmCjE9xYsPjMVW\nU84toRDvdfKOPnnGa7QMuSnF0fmx6pN51IfSTs52VtyCtsDw3SfmkHDdswKBgQC8\nkBthO1vcqE52HoJVRKiZXzECWQG/UsjVgwukVjY2G7jYmkceF9pDEaRYQeWnF8mU\nMRNvBf7Knl8t31zGdSqKo5fA6jTnrzlbYouymoeEwG9dP1DXBINDSDSi2RA/2k9D\nTSebKM76llL38KwGhamCFx86paaX+7LFeUe1+PgPAQKBgQDPLfqR+ifUaGBZDGNW\nIAGlJkPFoUvUs1FM6EMSewYOlkxMPqw1UEvCXVucT+K69B7gsVamYogffQ9FfowL\nPDkNOwKIVwB5vZBQnyA76uHAnWC2IfDKnK+FQ1k4qXiLQ5WYqtIi5OlqhsetX2JE\njh+LqREe1nOU6wu+sQXVexN+nw==\n-----END PRIVATE KEY-----\n",
  "client_email": "pocket-money@pocketmoney-150113.iam.gserviceaccount.com",
  "client_id": env('JSON_KEYFILE_CLIENT_ID'),
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/pocket-money%40pocketmoney-150113.iam.gserviceaccount.com"
}
